# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

target "Example" do
  pod "UITableViewDataSource-RACExtensions", :path => "../../"
end

# target "ExampleTests" do
#   pod 'Expecta'
# end

